version: '3.7'
networks:
  mongo-net:
    name: mongo-net
services:
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]
    ports:
    - "27018:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./scripts/file.key:/data/file.key"

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/data/file.key", "--replSet", "rs", "--journal", "--bind_ip_all" ]
    ports:
    - "27019:27017"
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./scripts/file.key:/data/file.key"

  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    command: bash -c "/usr/bin/mongod --keyFile /data/file.key --replSet rs --journal --bind_ip_all" 
    ports:
    - "27017:27017"
    links:
    - mongo1:mongo1
    - mongo2:mongo2
    restart: always
    networks:
      - mongo-net
    volumes:
    - "./scripts/setup.sh:/scripts/setup.sh"
    - "./scripts/file.key:/data/file.key"
